"""
Citadel Briefing Book Target Seed Loader
Adds all 11 remaining companies from the Fall 2025 Citadel SRM Briefing Book appendix.
Run once to populate companies.json. Safe to re-run — skips duplicates.

Usage:
    python3 citadel_targets.py
"""

import json
import os
from datetime import date

from profiler import compute_total_score, DATA_FILE

CITADEL_TARGETS = [
    # ── Group A: No Facility Clearance Required ───────────────────────────────
    {
        "company_name":            "CA-001 | RTC Aerospace",
        "hq_state":                "Chatsworth, CA / Fife, WA",
        "website":                 "rtcaerospace.com",
        "employee_count":          140,
        "known_revenue":           "~$49M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["336419", "332710", "332999"],
        "annual_award_volume_usd": 18_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "Aerojet Rocketdyne"],
        "jannaf_presence":         False,
        "trade_shows":             ["AIAA SciTech"],
        "publications":            [],
        "clearance_level":         "None",
        "specialized_facilities":  ["precision CNC", "SRM casing assembly"],
        "sbir_signal":             "None identified",
        "sub_award_confirmed":     False,
        "srm_role":                "Casing — Specialty Steel / Metal",
        "ebitda_pct_estimate":     0.175,
        "ebitda_band_low":         0.15,
        "ebitda_band_high":        0.20,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     False,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Precision machining of SRM casings, adapters, actuation components. Dual-site (CA + WA). ITAR-registered.",
    },
    {
        "company_name":            "TX-001 | Carbon-Carbon Advanced Technologies (C-CAT)",
        "hq_state":                "Grand Prairie, TX",
        "website":                 "c-cat.com",
        "employee_count":          110,
        "known_revenue":           "~$38M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["336415", "336419"],
        "annual_award_volume_usd": 22_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Aerojet Rocketdyne", "Northrop Grumman"],
        "jannaf_presence":         True,
        "trade_shows":             ["JANNAF"],
        "publications":            ["C/C ablative nozzle thermal performance"],
        "clearance_level":         "SECRET",
        "specialized_facilities":  ["carbon-carbon lay-up", "high-temp processing", "ablative nozzle machining"],
        "sbir_signal":             "Phase II awarded — solid propellant / rocket motor topic",
        "sub_award_confirmed":     True,
        "srm_role":                "Nozzle — Carbon-Carbon / Graphite Ablative",
        "ebitda_pct_estimate":     0.185,
        "ebitda_band_low":         0.15,
        "ebitda_band_high":        0.22,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 55,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "C/C hot-structure nozzle and throat components. One of very few domestic C/C ablative nozzle producers. Direct complement to Americarb CRP capability.",
    },
    {
        "company_name":            "NV-001 | Click Bond",
        "hq_state":                "Carson City, NV",
        "website":                 "clickbond.com",
        "employee_count":          185,
        "known_revenue":           "~$65M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["332999", "336419"],
        "annual_award_volume_usd": 30_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Lockheed Martin", "Northrop Grumman", "Raytheon / RTX"],
        "jannaf_presence":         False,
        "trade_shows":             ["MRO Americas", "AUSA"],
        "publications":            [],
        "clearance_level":         "None",
        "specialized_facilities":  ["adhesive bonding", "fastener installation tooling"],
        "sbir_signal":             "None identified",
        "sub_award_confirmed":     False,
        "srm_role":                "Other / Multi-role",
        "ebitda_pct_estimate":     0.215,
        "ebitda_band_low":         0.18,
        "ebitda_band_high":        0.25,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     False,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Aerospace structural fasteners and adhesive bonding systems. Broad multi-prime customer base. Platform-level fastener standardization value across all Citadel acquisitions.",
    },
    {
        "company_name":            "OH-001 | CTL Aerospace",
        "hq_state":                "Blue Ash, OH",
        "website":                 "ctlaerospace.com",
        "employee_count":          120,
        "known_revenue":           "~$42M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["336419", "336415"],
        "annual_award_volume_usd": 20_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["General Dynamics", "Northrop Grumman"],
        "jannaf_presence":         False,
        "trade_shows":             ["AUSA", "National Defense Industrial Association"],
        "publications":            [],
        "clearance_level":         "SECRET",
        "specialized_facilities":  ["composite layup", "bonded assembly", "autoclave"],
        "sbir_signal":             "Phase II awarded — adjacent topic (energetics, composite structures)",
        "sub_award_confirmed":     False,
        "srm_role":                "Casing — Carbon Fiber / Filament Winding",
        "ebitda_pct_estimate":     0.180,
        "ebitda_band_low":         0.15,
        "ebitda_band_high":        0.21,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 40,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Veteran-founded composite structures and bonded assemblies. Secret clearance. Midwest location adds geographic diversification to AR/AL/UT corridor concentration.",
    },
    {
        "company_name":            "MD-001 | Danko Arlington",
        "hq_state":                "Baltimore, MD",
        "website":                 "dankoarlington.com",
        "employee_count":          105,
        "known_revenue":           "~$37M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["332999", "332710"],
        "annual_award_volume_usd": 15_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["General Dynamics", "BAE Systems"],
        "jannaf_presence":         False,
        "trade_shows":             ["AUSA"],
        "publications":            [],
        "clearance_level":         "None",
        "specialized_facilities":  ["aluminum foundry", "bronze casting", "ITAR-controlled production"],
        "sbir_signal":             "None identified",
        "sub_award_confirmed":     False,
        "srm_role":                "Other / Multi-role",
        "ebitda_pct_estimate":     0.170,
        "ebitda_band_low":         0.14,
        "ebitda_band_high":        0.20,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     False,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "Owner approaching retirement (60+)",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Aluminum and bronze precision castings. HUBZone certified — preferential procurement weighting for DoD set-asides. ITAR-registered. Retirement owner signal.",
    },
    {
        "company_name":            "OK-001 | Nordam",
        "hq_state":                "Tulsa, OK",
        "website":                 "nordam.com",
        "employee_count":          270,
        "known_revenue":           "~$95M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["336419", "336415", "336411"],
        "annual_award_volume_usd": 40_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "Lockheed Martin", "Raytheon / RTX"],
        "jannaf_presence":         False,
        "trade_shows":             ["MRO Americas", "NBAA"],
        "publications":            [],
        "clearance_level":         "SECRET",
        "specialized_facilities":  ["composite bonding", "nacelle structures", "MRO"],
        "sbir_signal":             "None identified",
        "sub_award_confirmed":     False,
        "srm_role":                "Casing — Carbon Fiber / Filament Winding",
        "ebitda_pct_estimate":     0.150,
        "ebitda_band_low":         0.12,
        "ebitda_band_high":        0.18,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     False,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "Family-owned, second gen",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Large-format composite structures and MRO. May brush revenue ceiling — monitor. EBITDA at lower bound of criterion; value is in structural scale and multi-prime access.",
    },
    {
        "company_name":            "CO-001 | CoorsTek Defense (Technical Ceramics)",
        "hq_state":                "Golden, CO",
        "website":                 "coorstek.com",
        "employee_count":          240,
        "known_revenue":           "~$84M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["325180", "336415", "332999"],
        "annual_award_volume_usd": 35_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "Aerojet Rocketdyne", "Raytheon / RTX"],
        "jannaf_presence":         True,
        "trade_shows":             ["JANNAF", "AeroDef"],
        "publications":            ["Silicon carbide TPS performance", "ceramic throat insert erosion data"],
        "clearance_level":         "SECRET",
        "specialized_facilities":  ["ceramic sintering", "hot isostatic pressing", "thermal protection"],
        "sbir_signal":             "Phase II awarded — adjacent topic (energetics, composite structures)",
        "sub_award_confirmed":     True,
        "srm_role":                "Nozzle — Throat Inserts / TVC Components",
        "ebitda_pct_estimate":     0.185,
        "ebitda_band_low":         0.15,
        "ebitda_band_high":        0.22,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Technical ceramics division — throat inserts, TPS, SiC components. Note: CoorsTek is a large private company; a defense division carve-out may be the only viable structure.",
    },
    {
        "company_name":            "NM-001 | X-Bow Systems",
        "hq_state":                "Albuquerque, NM",
        "website":                 "x-bow.com",
        "employee_count":          100,
        "known_revenue":           "~$35M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["336415", "325920"],
        "annual_award_volume_usd": 28_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "L3Harris"],
        "jannaf_presence":         True,
        "trade_shows":             ["JANNAF", "AIAA SciTech"],
        "publications":            ["additive manufacturing solid propellant grains"],
        "clearance_level":         "SECRET",
        "specialized_facilities":  ["3D printing propellant grains", "hot fire test stand"],
        "sbir_signal":             "Phase III / direct-to-program (strongest signal)",
        "sub_award_confirmed":     True,
        "srm_role":                "Propellant — Mixing & Casting",
        "ebitda_pct_estimate":     0.05,
        "ebitda_band_low":         0.0,
        "ebitda_band_high":        0.10,
        "clearance_group":         "A",
        "cmmc_level_2":            False,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 60,
        "ma_signal":               "PE-backed seeking exit",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Venture/PE-backed. 3D-printed solid propellant SRMs. EBITDA below criterion — treated as strategic tech asset not a cash-flow target. Phase III SBIR confirms program integration.",
    },
    # ── Group B: Facility Clearance Likely Required ────────────────────────────
    {
        "company_name":            "AZ-001 | PacSci EMC",
        "hq_state":                "Chandler, AZ / Hollister, CA",
        "website":                 "pacsci-emc.com",
        "employee_count":          205,
        "known_revenue":           "~$72M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["325920", "336415", "332993"],
        "annual_award_volume_usd": 45_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "Aerojet Rocketdyne", "L3Harris"],
        "jannaf_presence":         True,
        "trade_shows":             ["JANNAF", "AUSA"],
        "publications":            ["pyrotechnic initiation reliability"],
        "clearance_level":         "TOP SECRET",
        "specialized_facilities":  ["energetic initiator production", "safety sequencing systems", "ATF-licensed"],
        "sbir_signal":             "Phase II awarded — solid propellant / rocket motor topic",
        "sub_award_confirmed":     True,
        "srm_role":                "Igniter / Initiator — Pyrotechnic",
        "ebitda_pct_estimate":     0.195,
        "ebitda_band_low":         0.16,
        "ebitda_band_high":        0.23,
        "clearance_group":         "B",
        "cmmc_level_2":            True,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 50,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Energetic initiation, safety & arming, pyrotechnic igniters. ATF explosive manufacturer license. CMMC L2 certified. Dual-site adds complexity but reduces single-point risk.",
    },
    {
        "company_name":            "CT-001 | Ensign-Bickford Aerospace & Defense (EBAD)",
        "hq_state":                "Simsbury, CT",
        "website":                 "ebad.com",
        "employee_count":          250,
        "known_revenue":           "~$87M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["325920", "336415", "332993"],
        "annual_award_volume_usd": 55_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "Aerojet Rocketdyne", "Raytheon / RTX", "L3Harris"],
        "jannaf_presence":         True,
        "trade_shows":             ["JANNAF", "AIAA", "AUSA"],
        "publications":            ["stage separation energetics", "flight termination systems"],
        "clearance_level":         "TOP SECRET",
        "specialized_facilities":  ["detonating cord", "EFI initiators", "flight termination systems", "ATF-licensed"],
        "sbir_signal":             "Phase III / direct-to-program (strongest signal)",
        "sub_award_confirmed":     True,
        "srm_role":                "Igniter / Initiator — Electrical",
        "ebitda_pct_estimate":     0.205,
        "ebitda_band_low":         0.17,
        "ebitda_band_high":        0.24,
        "clearance_group":         "B",
        "cmmc_level_2":            True,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "None identified",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Initiation, stage separation, flight termination, energetic systems. Phase III SBIR. Top-tier multi-prime access. Subsidiary of Day-Zimmermann — confirm parent company sale conditions.",
    },
    {
        "company_name":            "CA-002 | Marvin Engineering / The Marvin Group",
        "hq_state":                "Inglewood, CA",
        "website":                 "marvingroup.com",
        "employee_count":          258,
        "known_revenue":           "~$90M est.",
        "source":                  "Citadel SRM Briefing Book Fall 2025",
        "date_added":              str(date.today()),
        "naics_codes":             ["336419", "332999", "336415"],
        "annual_award_volume_usd": 50_000_000,
        "sam_registered":          True,
        "cage_code":               "",
        "prime_relationships":     ["Northrop Grumman", "Lockheed Martin", "Raytheon / RTX", "Boeing Defense"],
        "jannaf_presence":         False,
        "trade_shows":             ["AUSA", "Sea-Air-Space"],
        "publications":            [],
        "clearance_level":         "TOP SECRET",
        "specialized_facilities":  ["stores carriage systems", "weapons release", "missile interface hardware"],
        "sbir_signal":             "Phase II awarded — adjacent topic (energetics, composite structures)",
        "sub_award_confirmed":     True,
        "srm_role":                "Other / Multi-role",
        "ebitda_pct_estimate":     0.200,
        "ebitda_band_low":         0.16,
        "ebitda_band_high":        0.24,
        "clearance_group":         "B",
        "cmmc_level_2":            True,
        "cmmc_pathway_exists":     True,
        "niss_eligible":           True,
        "foreign_board_member":    False,
        "prime_concentration_pct": 0,
        "ma_signal":               "Family-owned, second gen",
        "broker_engaged":          False,
        "asking_price_usd":        None,
        "notes":                   "Stores carriage, heavy release systems, missile-to-airframe interfaces. 2nd gen family ownership — succession-script approach. Broad 4-prime portfolio significantly reduces concentration risk.",
    },
]


def load_companies() -> list[dict]:
    if not os.path.exists(DATA_FILE):
        return []
    with open(DATA_FILE) as f:
        return json.load(f)


def save_companies(companies: list[dict]) -> None:
    with open(DATA_FILE, "w") as f:
        json.dump(companies, f, indent=2)


def seed_citadel_universe() -> None:
    companies = load_companies()
    existing_names = {c["company_name"] for c in companies}

    added = 0
    for target in CITADEL_TARGETS:
        if target["company_name"] in existing_names:
            print(f"  [SKIP] {target['company_name']} — already in database")
            continue

        scored = compute_total_score(target)
        full_profile = {**target, **scored}
        companies.append(full_profile)
        added += 1

        grp = scored.get("clearance_group", "A")
        print(
            f"  [+] {target['company_name']:<48}  "
            f"Score: {scored['total_score']:>3}/115  "
            f"Group {grp}  {scored['tier_fit']}"
        )

    save_companies(companies)
    print(f"\n  Done. Added {added} companies. Pipeline total: {len(companies)}.")


if __name__ == "__main__":
    print("\n  Citadel Briefing Book — Target Universe Seed Loader")
    print("  ────────────────────────────────────────────────────")
    seed_citadel_universe()
